<?php
// $Id$

/**
 * @file
 * Notifications tools module
 */
/**
 * Implementation of hook_menu().
 */
function notifications_tools_menu() {
  $items['admin/messaging/subscriptions'] = array(
    'title' => 'Manage subscriptions',
    'description' => 'Manage existing subscriptions and queue.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notifications_tools_manage_subscriptions'),
    'access arguments' => array('administer notifications'),
    'file' => 'notifications_tools.pages.inc',
  ); 

  $items['admin/messaging/subscriptions/admin'] = array(
    'title' => 'Administer',
    'description' => 'Administer subscriptions.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer notifications'),
  );
  $items['admin/messaging/subscriptions/status'] = array(
    'title' => 'Status',
    'description' => 'Manage existing subscriptions and queue.',
    'page callback' => 'notifications_tools_status_page',
    'access arguments' => array('administer notifications'),
    'file' => 'notifications_tools.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );
  // Add a subtab to Notifications / Queue
  $items['admin/messaging/notifications/queue/configure'] = array(
    'title' => 'Configure',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'file' => 'notifications.admin.inc',
  );
  $items['admin/messaging/notifications/queue/operations'] = array(
    'title' => 'Operations',
    'description' => 'Queue operations.',
    'page callback' => 'notifications_tools_admin_queue',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer notifications'),
    'file' => 'notifications_tools.pages.inc',
  );
  // Test templates for node events
  if (module_exists('notifications_content')) {
    $items['admin/messaging/notifications/events/configure'] = array(
      'title' => 'Configure',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'access arguments' => array('administer site configuration'),
      'file' => 'notifications.admin.inc',
    );
    $items['admin/messaging/notifications/events/test'] = array(
      'title' => 'Test',
      'description' => 'Test event templates.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('notifications_tools_template_test_form'),
      'type' => MENU_LOCAL_TASK,
      'access arguments' => array('administer notifications'),
      'file' => 'notifications_tools.pages.inc',
    );
  }
  return $items;
}

