<?php
// $Id$

/**
 * @file
 * Notifications tools module
 */
/**
 * Implementation of hook_menu().
 */
function notifications_tools_menu() {
  $items['admin/messaging/notifications/queue'] = array(
    'title' => 'Queue processing',
    'description' => 'Parameters for processing queued notifications',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notifications_tools_queue_settings'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'file' => 'notifications_tools.pages.inc',
    'weight' => 100, // Show the last one, there are dangerous settings here.
  );
  $items['admin/messaging/notifications/queue/configure'] = array(
    'title' => 'Configure',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'file' => 'notifications.admin.inc',
  );
  $items['admin/messaging/notifications/queue/operations'] = array(
    'title' => 'Operations',
    'description' => 'Queue operations.',
    'page callback' => 'notifications_tools_admin_queue',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer notifications'),
    'file' => 'notifications_tools.pages.inc',
  );
  return $items;
}

